(this["webpackJsonpmy-app"]=this["webpackJsonpmy-app"]||[]).push([[0],[,,,,,,,,function(e,t,n){},function(e,t,n){},,function(e,t,n){},function(e,t,n){},function(e,t,n){},function(e,t,n){"use strict";n.r(t);var i=n(1),c=n.n(i),o=n(3),r=n.n(o),s=(n(8),n(9),n(0)),a=function(){return Object(s.jsxs)("div",{children:[Object(s.jsx)("hr",{Style:"border: 0.5px solid #F2F2EC;"}),Object(s.jsx)("footer",{children:Object(s.jsx)("p",{children:"All Right Reserved &copy By Golam Hakkani"})})]})},h=(n(11),function(){return Object(s.jsxs)("header",{className:"my-header",children:[Object(s.jsx)("h2",{children:"Golam Hakkni"}),Object(s.jsx)("button",{children:"Sign in"})]})}),d=function(){return Object(s.jsx)("div",{children:Object(s.jsxs)("div",{class:"traning",children:[Object(s.jsx)("h2",{children:"Personal Training for $30"}),Object(s.jsx)("p",{children:"If you need career guide, personal interview tips, mock interview, Life Coaching, or anything else, you can book me for 30 min. Just pay $30 via paypal to Codinism (my company) and then book a time slot You can Book me"})]})})},l=function(e){return Object(s.jsx)("div",{class:"cards-style",children:Object(s.jsxs)("div",{class:"tutorials",children:[Object(s.jsx)("h2",{children:e.title}),Object(s.jsx)("p",{children:e.desc}),Object(s.jsx)("button",{children:"View Details ... "})]})})},j=(n(12),function(){return Object(s.jsxs)("main",{children:[Object(s.jsxs)("section",{className:"leftSide",children:[Object(s.jsxs)("div",{class:"js-config",children:[Object(s.jsx)("h3",{children:"JS Confusing Parts"}),Object(s.jsxs)("p",{children:["Understand ",Object(s.jsx)("span",{Style:"color: red",children:"this, scope, hoisting, closure, inheritance, bind, call, apply, prototype, event delegation, dom,"})," timers and many more caveats."]})]}),Object(s.jsxs)("div",{class:"cards",children:[Object(s.jsx)(l,{title:"HTML",desc:"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag"}),Object(s.jsx)(l,{title:"CSS",desc:"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag"}),Object(s.jsx)(l,{title:"Java Script",desc:"an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"JQuery",desc:"an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"Angular Js",desc:"an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"Wordpress",desc:"Wordpress function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"React",desc:"React is a function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"Json Api",desc:"Json Api is a function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "}),Object(s.jsx)(l,{title:"PHP",desc:"Php Api is a function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag Unhandled promise rejection. This error originated either by throwing inside of "})]})]}),Object(s.jsxs)("section",{className:"RightSide",children:[Object(s.jsx)(d,{}),Object(s.jsx)(d,{})]})]})}),b=(n(13),function(){return Object(s.jsxs)("section",{className:"sub-header",children:[Object(s.jsxs)("h1",{children:["Exclusive React Workshop for",Object(s.jsx)("br",{})," beginners!"]}),Object(s.jsxs)("p",{children:["Once in a year opportunity to learn and build your ",Object(s.jsx)("span",{Style:{color:"#0076B8"},children:"first React app"})]}),Object(s.jsx)("button",{children:"Learn More"})]})});var u=function(){return Object(s.jsxs)("div",{className:"App",children:[Object(s.jsx)(h,{}),Object(s.jsx)(b,{}),Object(s.jsx)(j,{}),Object(s.jsx)(a,{})]})},p=function(e){e&&e instanceof Function&&n.e(3).then(n.bind(null,15)).then((function(t){var n=t.getCLS,i=t.getFID,c=t.getFCP,o=t.getLCP,r=t.getTTFB;n(e),i(e),c(e),o(e),r(e)}))};r.a.render(Object(s.jsx)(c.a.StrictMode,{children:Object(s.jsx)(u,{})}),document.getElementById("root")),p()}],[[14,1,2]]]);
//# sourceMappingURL=main.f511d3c3.chunk.js.map